security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        whatsapp:
            id: App\Security\User\UserProvider

    role_hierarchy:
        ROLE_USER: ROLE_USER

    firewalls:
        main:
            pattern: ^/admin
            form_login:
                provider: whatsapp
                check_path: login_check
                csrf_token_generator: security.csrf.token_manager
                default_target_path: home_index
                always_use_default_target_path: true
            logout:
                path: logout
                target: login
            anonymous:    true

        assets:
            pattern: ^/(css|images|img|js|lib|fonts|bundles)/
            security: false

        dev:
            pattern:  ^/(_(profiler|wdt))/
            security: false

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_USER }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
